|  Column name  |  Description  |
| ----- | ------- |
| Num_posts        | Number of total posts that the user has ever posted   |
| Num_following    | Number of following                                   |
| Num_followers    | Number of followers                                   |
| Biography_length | Length (number of characters) of the user's biography |
| Picture_availability | Value 0 if the user has no profile picture, or 1 if has |
| Link_availability| Value 0 if the user has no external URL, or 1 if has |
| Average_caption_length | The average number of character of captions in media |
| Caption_zero     | Percentage (0.0 to 1.0) of captions that has almost zero (<=3) length |
| Non_image_percentage | Percentage (0.0 to 1.0) of non-image media. There are three types of media on an Instagram post, i.e. image, video, carousel
| Engagement_rate_like | Engagement rate (ER) is commonly defined as (num likes) divide by (num media) divide by (num followers)
| Engagement_rate_comment | Similar to ER like, but it is for comments |
| Location_tag_percentage | Percentage (0.0 to 1.0) of posts tagged with location |
| Average_hashtag_count   | Average number of hashtags used in a post |
| Promotional_keywords | Average use of promotional keywords in hashtag, i.e. regrann, contest, repost, giveaway, mention, share, give away, quiz |
| Followers_keywords | Average use of followers hunter keywords in hashtag, i.e. follow, like, folback, follback, f4f|
| Cosine_similarity  | Average cosine similarity of between all pair of two posts a user has |
| Post_interval      | Average interval between posts (in hours) |
| real_fake          | r (real/authentic user), f (fake user/bought followers) |

# Q1: Import labraries

In [107]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Q2: Read instagram_users.csv file

In [109]:
df = pd.read_csv("/content/instagram_users.csv")

# Q3: Split tha dataset into training and testing

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
df.head()

Num_posts  Num_following  Num_followers  Biography_length  \
0          44             48            325                33   
1          10             66            321               150   
2          33            970            308               101   
3          70             86            360                14   
4           3             21            285                73   

   Picture_availability  Link_availability  Average_caption_length  \
0                     1                  0                      12   
1                     1                  0                     213   
2                     1                  1                     436   
3                     1                  0                       0   
4                     1                  0                      93   

   Caption_zero  Non_image_percentage  Engagement_rate_like  \
0           0.0                   0.0                  0.00   
1           0.0                   1.0                 14.39   
2           0.0                   1.0                 10.10   
3           1.0                   0.0                  0.78   
4           0.0                   0.0                 14.29   

   Engagement_rate_comment  Location_tag_percentage  Average_hashtag_count  \
0                     0.00                    0.000                    0.0   
1                     1.97                    0.000                    1.5   
2                     0.30                    0.000                    2.5   
3                     0.06                    0.000                    0.0   
4                     0.00                    0.667                    0.0   

   Promotional_keywords  Followers_keywords  Cosine_similarity  Post_interval  \
0                   0.0               0.000           0.111111       0.094985   
1                   0.0               0.000           0.206826     230.412857   
2                   0.0               0.056           0.572174      43.569939   
3                   0.0               0.000           1.000000       5.859799   
4                   0.0               0.000           0.300494       0.126019   

  real_fake  
0      fake  
1      fake  
2      fake  
3      fake  
4      fake

In [117]:
df2 = pd.DataFrame(df)

In [118]:
X = df2[[ "Num_following" ,	"Num_followers" ,	"Biography_length" ,	"Picture_availability" ,"Link_availability" ,	
        "Average_caption_length" ,"Caption_zero" ,"Non_image_percentage" ,"Engagement_rate_like" ,"Engagement_rate_comment" 
        ,	"Location_tag_percentage"	, "Average_hashtag_count"	, "Promotional_keywords" ,	"Followers_keywords" ,	"Cosine_similarity"	,"Post_interval"]]
y = df2["real_fake"] 

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

# Q4: Build three machine models 

## Q4.1: The first machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [120]:
from sklearn.tree import DecisionTreeClassifier

In [121]:
dtree = DecisionTreeClassifier()

In [122]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [123]:
predictions = dtree.predict(X_test)

In [148]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [125]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

        fake       0.85      0.86      0.85      9495
        real       0.86      0.85      0.85      9779

    accuracy                           0.85     19274
   macro avg       0.85      0.85      0.85     19274
weighted avg       0.85      0.85      0.85     19274



In [126]:
print(accuracy_score(y_test,predictions))

0.8524955899138736


In [137]:
print(confusion_matrix(y_test,predictions))

[[8131 1364]
 [1479 8300]]


## Q4.2: The second machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [142]:
from sklearn.ensemble import RandomForestClassifier


clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [143]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8995019196845492


In [151]:
confusion_matrix(y_test, y_pred)

array([[7975, 1520],
       [ 417, 9362]])

## Q4.3: The third machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [152]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)

In [154]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

Accuracy: 0.8064231607346685


In [156]:
confusion_matrix(y_test , predictions)

array([[7477, 2018],
       [1713, 8066]])